---
title: "clase 7"
author: "Christian Limbert Paredes Aguilera"
date: "2022-12-07"
output: pdf_document
---

## Cointegración

- Son relaciones de equilibro en varias variables.

- La relación de cointegración se expresa las variables en niveles, nunca diferenciadas a largo plazo.

- El largo plazo se mide en niveles, ya que si la medimos en diferenciación estaríamos midiendo la variación cuando se tiene una unidad más de tiempo, es decir a corto plazo.

- Se quiere saber si entre mis variables habrá relaciones de equilibrio. Esto con el contraste de Engle-Granger. Pero estos contraste son antiguas y existen mejores técnicas con mejores propiedades.

### Contraste de Engle-Granger

- Es un constrate antiguo, pero no quiere decir que ya no se use.

### Contraste de Johansen
- El contraste de Johansen, es una alternativa mejor a Engle-Granger. 
-Consiste en conocer cuanta relaciones de cointregrantes existen entre mis variables. En caso de que existan, cuantas hay?

$$\triangle X_t=\Pi X_{t-1}+\epsilon_t$$

Existen dos contrastes para determinar el número de vectores de cointegración:

##### Constrate de la traza

$\lambda_{traza} = -T\sum\limits_{i=r+1}^n \ln(1-\lambda_i)$. con las $n$ raíces de la matriz $\prod (\lambda_i)$ se realiza el contraste:

$$
\left\{
\begin{array}{rl}
  H_0: & \mbox{número vectores de cointegración} \leq r\\
  H_1: & \mbox{número vectores de cointegración} > r
\end{array}
\right.
$$


##### Contraste del máximo autovalor

$\lambda_{max} = -T\ln(1-\lambda_{r+1})$.  Se concentra de manera sucesiva:

$$
\left\{
\begin{array}{rl}
  H_0: & \mbox{número vectores de cointegración} = r\\
  H_1: & \mbox{número vectores de cointegración} = r+1.
\end{array}
\right.
$$

#### Cuestión importante

- Me interesa saber que pasará en el largo plazo si existe una variación en el corto plazo. Para ello se utiliza los MECANISMOS DE CORRECCIÓN DE ERROR (MCE/ECM)

- El MCE nos indicará ese comportamiento a corto plazo, que pasa si me desvío en el corto plazo.

- Si $Y_t$ y $X_t$ están cointegradas, se puede reflejar el ECM (Cómo vuelvo al equilibro cuando se a producido un desequilibro) del siguiente modo:

$$\triangle Y_t = \alpha_1\triangle X_t + \alpha_2 \hat{u}_{i-1}+u_i.$$

$\hat{u}_t$ es el error de la ecuación de cointegración entre $X_t$ e $Y_t$, $\alpha_1$ refleja la relación de corto plazo entre las variables  
- $\alpha_2$ es el término más importante llamado TÉRMINO DE CORRECCIÓN DEL ERROR, y el valor nos dice cómo se ajustará las variables ante desviación de largo plazo y por tanto como volverán al equilibro si han sufrido algún tipo de desequilibro transitorio. QUE PASA SI ME DESVIO?, lo puedeo determinar con $\alpha_2$.

El residuo estimado $\hat{u}_t$ estará dado por:

$$y_{t-1}=\beta_0+\beta_1 x_{t-1}\quad \Rightarrow \quad \hat{u}_{t-1}=t_{t-1}-\beta_0-\beta_1x_{t-1}$$

esto es lo que a sucedido frente a lo que debería suceder. 

- $\alpha_2$ debe ser NEGATIVO, es decir contra-resta a lo que a sucedido. Se puede interpretar directamente como: Qué porcentaje del desequilibrio que se a producido en un momento del tiempo se corregirá en el momento siguiente. Al final del cabo es la diferencia entre dos momentos del tiempo. Cuanto podre corregir, mucho, poco, nada. Es decir, el $71\%$ del momento $t$ se va a corregir en el momento $t+1$.


### Resumen

- No tenemos que analizar siempre la cointegración.

¿Cómo realizamos la estimación de la relación entre series temporales según la naturaleza de éstas?

- Con series estacionarias: se emplean los procedimiento habituales (MCO,etc)

- con series no estacionarias de diferente orden: No se puede estimar la relación.

- Con series no estacionarias del mismo orden pero no cointegradas: No se puede estimar la relación porque existe regresión espuria.

- Con series no estacionarias pero cointegradas: Se emplean los procedimientos habituales para la estimación de la relación a largo plazo y el modelo de correción del error pra las relaciones de corto plazo.
 
 
## Ejemplo: Ley de Okun.

```{r}
```
