---
title: "Clase 3"
author: "Christian Limbert Paredes Aguilera"
date: "2022-12-01"
output: pdf_document
---

## 3.3 Modelización lineal univariante

- Querremos encontrar un patrón.

La estructura básica será:

\begin{center}
Serie de tiempo = parte sistemática + parte aleatoria
\end{center}


Parte sistemática = Recoge el patrón de regularidad.

- La forma más habitual de representar la fórmula sera:

$$Y_t=\pi_1T_{t-1}+\pi_2 Y_{t-2}+\ldots + a_t, \quad \forall t, t=1,2,\ldots\qquad (A)$$

En este caso depende de su pasado y alguna perturbación.

$a_t$ = ruido blanco.
$\pi_1T_{t-1}+\pi_2 Y_{t-2}$ = pasado.
Siempre que se tenga una ecuación como la de arriba se esconderá un polinomio. 

- Las condiciones generales serán:

  - Que el proceso sea no anticipante (el presente no viene determinado por el futuro.)
  - Que el proceso sea invertible (el proceso depende de manera convergente de su pasado; la influencia del pasado es menor conforme nos alejamos en el tiempo)

- El modelo anterior se puede escribir como la combinación nieal:

$$Y_t=a_t+\varphi_1 Y_{t-1}+\varphi_2T_{t-2}+\cdots, \qquad \forall t, \; t=1,2,\ldots. \qquad (B)$$

- El modelo lineal general se puede representar de 3 formas:

  - Representación puramente autorregresiva (A) o (AR) con parámetro p, que es la máxima dependencia. 
  - Representación puramente de medias móvibles (B) o (MA) con parámetro q, que representa la máxima dependencia.
    - (p,q) significa el retardo máximo de mi especificación.
  - Representación finita (C) - formato general
  
  
## Procesos autorregresivos AR(p)

Sigue un proceso AR cuando lo puede expresar de esta forma:

$$Y_t = \phi_1 T_{t-1}+\phi_2 Y_{t-2}+\ldots + \phi_p Y_{t-p}+ a_t$$

Depende de su pasado hasta un cierto de tiempo más su perturbación.

Podemos expresarlo en formato polinomio:

$$(1-\phi_1 L - \phi_2 L^2-\cdots - \phi L^P)Y_t=a_t$$

  - $L = Retardando$ y $L^P=Periodos\; terdados.$

  - $a_t$ ruido blanco $N(0,\sigma^2)$
  
Se puede ver la siguiente forma simple

$$LT_T=T_{t-1}$$

Y si $L^2$, significa que estamos retardando dos periodos y así sucesivamente.

Cuanto menos mejor.

#### Parseo aleatorio

o $AR(1)$

$$Y_t=T_{t-1}=a_t \quad \Rightarrow \quad \triangle T_t=a_t,\qquad a_t\sim N(0,\sigma^2)$$

Donde $a_t$ es aleatoria. 

El modelo de paseo aleatorio $AR(1)$ está definido por

$$Y_t=Y_{t-1}+a_t \quad \Rightarrow \quad \triangle Y_t=a_t$$

Es decir, el modelo es completamente aleatorio.
  
### Identificación de AR(p)

Identificamos AR por la función de autocorrelación. 

  - La forma de una autocorrelación simple sera de manera exponencial negativa. Es decir, que decaiga con el tiempo.

  - La forma de una autocorrelación parcial sera, con una barra o dos dependiendo el parámetro.

Se los llama también procesos de memoria larga. Porque dependen de su pasado.


### Proceso de medias móviles MA(q)

- Son modelos donde las variables dependa de la perturbación.

- Carece de memoria

$$Y_t = a_t-\theta_1a_{t-1}-\theta_2a_t-\cdots - \theta_q a_{t-q}.$$

con $a_t$ proceso de ruido blanco y $\theta$ parámetros del modelo.

Polinomialmente es:

$$Y_t=(1-\theta_1L-\theta_2 L^2 - \cdot -\theta_q L^q)a_t$$

- Se puede ver cuando tienen series erraticas.

- Parece menos intuiditivo que AR, pero a través del operador de retardos se comprueba que:

$$Y_t=(1-\theta L)a_t \quad \Rightarrow \quad Y_t=a_t+\theta T_{t-1}-\theta^2 Y_{t-2}+\theta^3 Y_{t-3}+\ldots$$

- Carece de memoria. Por lo identificamos a MA contrariamente a AR

  - La forma de una autocorrelación simple sera, con una barra o dos dependiendo el parámetro.

  - La forma de una autocorrelación parcial sera de manera exponencial negativa. Es decir, que decaiga con el tiempo.
  
- Absorve cualquier shock de manera rápida. Es decir, se desvanece rápidamente a través del tiempo.

- NO SE PODRÁ MODELAR NINGÚNA SERIE DE TIEMPO SI NO ES ESACIONARIA.

### Ejemplso
- Si vemos todos los valores temporales de AC tienden a $1$ y PAC el primer dato igual a $1$  es no estacionaria. Donde tendremos que hacer una transformación a proceso estacionario.
- No podremos modelizar una seria de tiempo si el modelo  es no estacionaria. Debe ser estacionaria.
- Si $AC$ y $PAC$ tiende a cero entonces es ruido blanco.


## Procesos autorregresivos de medias móviles ARMA(p,q)

Es un proceso con la forma 

$$Y_t=\phi_1 Y_{t-1}+\cdots + \phi_p Y_{t-p}+\theta_1a_{t-1}+\cdots + \theta_q a_{t-q}+a_t$$

### Cómo se identifica ARMA

Ejemplo ARMA(1,1)
- Autocorrelación Simple: Solo una barra

- Autocorrelación Parcial: barras asimetricas.

## Proceso autorregresivo integrado y de media móviles ARIMA(p,d,q)

- d = significa que hemos convertido una serie no estacionaria en estacionaria. o integramos la función de orden 1.

$$Y_t^d=\phi_1 Y_{t-1}^d +\cdots + \phi_p Y_{t-p}^d+\theta_1a_{t-1}^d+\cdots + \theta_q a_{t-q}^d+a_t^d$$

##### Ejemplo
- $ARIMA(0,1,2)$ = no existe AR con dos MA y  la transformamos de orden 1

## Pruebas de Box-Pierce y Ljung-Box

Planteamiento del contrasate 
$$
\left\{
\begin{array}{rl}
  H_0: & \rho_1=\rho_2=\cdots = \rho_s = 0\\
  H_1: & \mbox{algún} \; \rho_k \neq 0.
\end{array}
\right.
$$

Los residuos no pueden estar correlacionadas consigo misma.

- Sirve para validar un modelo. Un valor bajo es indicio de que los residuos no son ruido blanco. Comprobamos que la media es cero y la varianza es constante. Por lo tanto tenemos un problema de ruido blanco. Podemos tambien decir que los residuos están correlacionados con su pasado. 

## Metodoloǵia de Box-Jenkins:

Nos ayuda a:

- Generar una clase de modelos que describan series de tiempo reales.
- Determinar el procedimiento para hallar el mejor modelo de esa clase para una serie dada.

### Etapas de la metodología.

- Identificación.
- Estimación.
- Diagnóstico/validación.
-Predicción.

